// Serves TimesFM batch forecasts generated by GitHub Actions
// (see /forecast/README.md).
//
// Design: forecast DATA is decoupled from deploys. Files ship in git (fast
// path), but the service also fetches fresh JSON from GitHub raw at runtime
// and revalidates every few minutes — so new workflow results appear on the
// site without waiting for a Render redeploy. Gracefully returns null when
// forecasts don't exist anywhere yet.

import { readFileSync, statSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GH_REPO = process.env.GH_REPO || 'bhalekarabhijit/alphabets';
const REMOTE_BASE = `https://raw.githubusercontent.com/${GH_REPO}/main/forecast`;
const REVALIDATE_MS = 5 * 60 * 1000; // re-check GitHub for fresher data
const FETCH_TIMEOUT_MS = 15000;

export const UNIVERSES = [
  { id: 'nifty50', label: 'Nifty 50', description: 'Top 50 largecap stocks' },
  { id: 'next50', label: 'Nifty Next 50', description: 'Next 50 largecap stocks' },
  { id: 'midcap50', label: 'Nifty Midcap 50', description: 'Top 50 midcap stocks' },
  { id: 'smallcap50', label: 'Nifty Smallcap 50', description: 'Top 50 smallcap stocks' },
];

const fileCache = new Map(); // disk path -> { mtime, data }
const mem = new Map();       // `${kind}:${universe}` -> { doc, fetchedAt }

function loadFile(path) {
  try {
    const mtime = statSync(path).mtimeMs;
    const hit = fileCache.get(path);
    if (hit && hit.mtime === mtime) return hit.data;
    const data = JSON.parse(readFileSync(path, 'utf-8'));
    fileCache.set(path, { mtime, data });
    return data;
  } catch {
    return null;
  }
}

function loadFirst(paths) {
  for (const p of paths) {
    const data = loadFile(p);
    if (data) return data;
  }
  return null;
}

function forecastDir() {
  return join(__dirname, '../../forecast');
}

// Per-universe files (forecasts-nifty50.json), with fallback to the
// legacy flat filenames for nifty50 (written by older workflow runs).
function diskPaths(kind, universe) {
  const dir = forecastDir();
  const prefix = kind === 'picks' ? 'picks' : 'forecasts';
  if (universe === 'nifty50') {
    return [join(dir, `${prefix}-nifty50.json`), join(dir, `${prefix}.json`)];
  }
  return [join(dir, `${prefix}-${universe}.json`)];
}

function remoteUrls(kind, universe) {
  const prefix = kind === 'picks' ? 'picks' : 'forecasts';
  const urls = [`${REMOTE_BASE}/${prefix}-${universe}.json`];
  if (universe === 'nifty50') urls.push(`${REMOTE_BASE}/${prefix}.json`);
  return urls;
}

async function fetchRemoteJson(url) {
  try {
    const res = await fetch(url, {
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      headers: { 'User-Agent': 'Alphabets/1.0' },
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

// Best-effort write-through so restarts within a deploy stay instant.
// (Render disk is ephemeral — git + GitHub raw remain source of truth.)
function persistDisk(kind, universe, doc) {
  try {
    const prefix = kind === 'picks' ? 'picks' : 'forecasts';
    writeFileSync(join(forecastDir(), `${prefix}-${universe}.json`), JSON.stringify(doc));
    fileCache.delete(join(forecastDir(), `${prefix}-${universe}.json`));
  } catch { /* read-only FS? ignore */ }
}

async function getDoc(kind, universe) {
  const key = `${kind}:${universe}`;
  const now = Date.now();
  const entry = mem.get(key);
  if (entry && now - entry.fetchedAt < REVALIDATE_MS) return entry.doc;

  let doc = loadFirst(diskPaths(kind, universe)) || entry?.doc || null;

  for (const url of remoteUrls(kind, universe)) {
    const remote = await fetchRemoteJson(url);
    if (!remote) continue;
    if (!doc || (remote.generated_at && remote.generated_at !== doc.generated_at)) {
      doc = remote;
      persistDisk(kind, universe, remote);
      break;
    }
    // Remote matches what we have — still fresh enough to re-stamp.
    break;
  }

  mem.set(key, { doc, fetchedAt: now });
  if (doc && doc.generated_at !== entry?.doc?.generated_at) {
    console.log(`📈 TimesFM ${kind} [${universe}] as of ${doc.generated_at}`);
  }
  return doc;
}

function normalizeTicker(t) {
  return t.toUpperCase().trim().replace(/\.NS$/, '').replace(/\.BO$/, '');
}

export async function getForecast(roughTicker, universe = 'nifty50') {
  const data = await getDoc('forecasts', universe);
  if (!data || !data.forecasts) return null;
  const key = normalizeTicker(roughTicker);
  // forecasts.json is keyed by bare symbol (RELIANCE) for readability.
  const fc = data.forecasts[key]
    || data.forecasts[`${key}.NS`]
    || data.forecasts[`${key}.BO`];
  if (!fc) return null;
  return { ...fc, generated_at: data.generated_at, model: data.model || 'timesfm' };
}

export async function getTimesfmPicks(universe = 'nifty50') {
  return (await getDoc('picks', universe)) || null;
}

// Availability summary for the universes endpoint (counts + timestamps).
export async function getUniverseStatus() {
  return Promise.all(UNIVERSES.map(async (u) => {
    const picks = await getDoc('picks', u.id);
    return {
      ...u,
      available: !!picks,
      generated_at: picks?.generated_at || null,
      picks_count: picks?.picks?.length || 0,
      universe_size: picks?.universe_size || 0,
    };
  }));
}
