// Serves TimesFM batch forecasts generated by GitHub Actions
// (see /forecast/README.md). Zero runtime cost: the Node server only
// reads JSON files. Gracefully returns null when forecasts don't exist.

import { readFileSync, statSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export const UNIVERSES = [
  { id: 'nifty50', label: 'Nifty 50', description: 'Top 50 largecap stocks' },
  { id: 'next50', label: 'Nifty Next 50', description: 'Next 50 largecap stocks' },
  { id: 'midcap50', label: 'Nifty Midcap 50', description: 'Top 50 midcap stocks' },
  { id: 'smallcap50', label: 'Nifty Smallcap 50', description: 'Top 50 smallcap stocks' },
];

const fileCache = new Map(); // path -> { mtime, data }

function loadFile(path) {
  try {
    const mtime = statSync(path).mtimeMs;
    const hit = fileCache.get(path);
    if (hit && hit.mtime === mtime) return hit.data;
    const data = JSON.parse(readFileSync(path, 'utf-8'));
    fileCache.set(path, { mtime, data });
    return data;
  } catch {
    return null;
  }
}

// Per-universe files (forecasts-nifty50.json), with fallback to the
// legacy flat filenames for nifty50 (written by older workflow runs).
function universePaths(universe) {
  const dir = join(__dirname, '../../forecast');
  if (universe === 'nifty50') {
    return {
      forecasts: [join(dir, 'forecasts-nifty50.json'), join(dir, 'forecasts.json')],
      picks: [join(dir, 'picks-nifty50.json'), join(dir, 'picks.json')],
    };
  }
  return {
    forecasts: [join(dir, `forecasts-${universe}.json`)],
    picks: [join(dir, `picks-${universe}.json`)],
  };
}

function loadFirst(paths) {
  for (const p of paths) {
    const data = loadFile(p);
    if (data) return data;
  }
  return null;
}

function normalizeTicker(t) {
  return t.toUpperCase().trim().replace(/\.NS$/, '').replace(/\.BO$/, '');
}

export function getForecast(roughTicker, universe = 'nifty50') {
  const data = loadFirst(universePaths(universe).forecasts);
  if (!data || !data.forecasts) return null;
  const key = normalizeTicker(roughTicker);
  // forecasts.json is keyed by bare symbol (RELIANCE) for readability.
  const fc = data.forecasts[key]
    || data.forecasts[`${key}.NS`]
    || data.forecasts[`${key}.BO`];
  if (!fc) return null;
  return { ...fc, generated_at: data.generated_at, model: data.model || 'timesfm' };
}

export function getTimesfmPicks(universe = 'nifty50') {
  const data = loadFirst(universePaths(universe).picks);
  return data || null;
}

// Availability summary for the universes endpoint (counts + timestamps).
export function getUniverseStatus() {
  return UNIVERSES.map(u => {
    const picks = loadFirst(universePaths(u.id).picks);
    return {
      ...u,
      available: !!picks,
      generated_at: picks?.generated_at || null,
      picks_count: picks?.picks?.length || 0,
      universe_size: picks?.universe_size || 0,
    };
  });
}
